accounts/urls.py
from django.conf.urls import url
from django.urls import path
from accounts import views


urlpatterns = [
    path("send-email", views.send_login_email, name="send_login_email"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
]

lists/urls.py
from django.urls import path

from lists import views

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:id>", views.view_list, name="view_list"),
]

superlists/urls.py
from django.contrib import admin
from django.urls import include, path
from lists import views

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("lists/", include("lists.urls")),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)

from django.db import models


class ListUserManager(BaseUserManager):
    def create_user(self, email):
        ListUser.objects.create(email=email)

    def create_superuser(self, email, password):
        self.create_user(email)


class ListUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(primary_key=True)
    USERNAME_FIELD = "email"

    objects = ListUserManager()

    @property
    def is_staff(self):
        return self.email == "harry.percival@example.com"

    @property
    def is_active(self):
        return True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(max_length=255)

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", kwargs={"id": self.id})


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey("List", default=None, on_delete=models.CASCADE)

    class Meta: 
        ordering = ("id",)
        unique_together = ("list", "text",)
        
        
    def __str__(self) -> str:
        return self.text

lists/forms.py
from attr import fields
from django import forms

from lists.models import Item


EMPTY_ITEM_ERROR = "You can't have an empty list item"


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control input-lg",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

accounts/views.py
import sys
import uuid

from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout


from accounts.models import Token


def send_login_email(request):
    email = request.POST["email"]
    uid = str(uuid.uuid4())
    Token.objects.create(email=email, uid=uid)
    print("saving uid", uid, "for email", email, file=sys.stderr)
    url = request.build_absolute_uri(f"/accounts/login?uid={uid}")
    send_mail(
        "Your login link for Superlists",
        f"Use this link to log in:\n\n{url}",
        "noreply@superlists",
        [email],
    )

    return render(request, "login_email_sent.html")


def login(request):
    print("login view", file=sys.stderr)
    uid = request.GET.get("uid")
    user = authenticate(uid=uid)
    if user is not None:
        auth_login(request, user)
    return redirect("/")


def logout(request):
    auth_logout(request)
    return redirect("/")    

lists/views.py
from django.forms import ValidationError
from django.shortcuts import redirect, render
from lists.forms import ItemForm

from lists.models import Item, List


def home_page(request):
    return render(request, "home.html", {"form": ItemForm()})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, "home.html", {"form", form})


def view_list(request, id):
    list_ = List.objects.get(id=id)
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)

    return render(request, "list.html", {"list": list_, "form": form})

accounts/templates/login_email_sent.html
<html>
<h1>Email sent</h1>

<p>Check your email, you'll find a message with a link that will log you into
the site.</p>

</html>

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/base.css" rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <div class="navbar">
        {% if user.is_authenticated %}
          <p>Logged in as {{ user.email }}</p>
          <p><a id="id_logout" href="{% url 'logout' %}">Log out</a></p>
        {% else %}
          <form method="POST" action ="{% url 'send_login_email' %}">
            Enter email to log in: <input name="email" type="text" />
            {% csrf_token %}
          </form>
        {% endif %}
      </div>
  
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 p-5 mb-4 bg-light rounded-3">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
              {% csrf_token %}
              {{ form.text }} 
              {% if form.errors %}
              <div class="form-group has-error">
                <div class="help-block">{{ form.text.errors }}</div>
              </div>
              {% endif %}
            </form>
          </div>
        </div>
      </div>

      <div class="row d-flex justify-content-center mt-3">
        <div class="col-md-6 col-md-offset-3">
          {% block table %} {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lists/templates/home.html
{% extends "base.html" %}

{% block header_text %}
  Start a new To-Do list
{% endblock header_text %}

{% block form_action %}
  {% url "new_list" %}
{% endblock form_action %}

lists/templates/list.html
{% extends "base.html" %}

{% block header_text %}Your To-Do list{% endblock header_text %}

{% block form_action %}
{% url "view_list" list.id %}
{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock table %}